server:
  port: 8080
spring:
  profiles:
    active: dev

dummyjson:
  api:
    base-url: https://dummyjson.com

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
      path-mapping:
        health: /health


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html